### ISSUE TITLE
Additional Reviewers for DefinitelyTyped PRs

### ISSUE THREAD

**Issue by GlenCFL** [GlenCFL/atom-typings#11]
The DefinitelyTyped pull requests currently take too long. Due to there only being a single author on the definitions, we have to wait for the YSYL label to be added following 5 days of inactivity. If there are any merge conflicts prior to the pull request being merged, then we have to rebase and reset that clock. This has resulted in [#20900](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20900) being delayed several times.

In order to get around this, we need more people willing to review pull requests made to `@types/atom` on DefinitelyTyped. I am not looking for people to simply accept any pull request, but to actually review changes and keep things sane. In order to be added, you will need to make a pull request to DefinitelyTyped adding yourself as an author, likely mentioning this issue within it.

In [#19993](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19993), @smhxx was added as an author just prior to the rewrite being pulled, so they seem like a good first candidate.

**Comment by smhxx** [comment]
That sounds like a good idea. Having at least two authors to review each other's changes (in order to make use of the express lane rather than the slow "you snooze, you lose" route) should make it easier to get those changes published in a more timely manner. I imagine that, since I was previously listed as an author on `@types/atom`, it should be relatively easy to get myself added back on. I'll go ahead and make the request and see if they'll put me back on.
