### ISSUE TITLE
Cannot find namespace 'Atom'

### ISSUE THREAD

**Issue by shd101wyy** [GlenCFL/atom-typings#9]
Hi there, 

I was trying to develop the [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced) package in **vscode**. When I build it, I get the error `Cannot find namespace 'Atom'`.  

![screenshot from 2017-11-05 16-43-35](https://user-images.githubusercontent.com/1908863/32419944-7cfb19c0-c248-11e7-9855-8c63ae2dff57.png)

Any idea how to solve the problem?
(It used to be working fine on my Mac, but I just switched to ubuntu and it stopped working)

Thank you! :)

**Comment by shd101wyy** [comment]
More information:  

![screenshot from 2017-11-05 16-52-55](https://user-images.githubusercontent.com/1908863/32420004-cdf8b624-c249-11e7-8be8-7c75ea0fb58c.png)

**Comment by GlenCFL** [comment]
This doesn't have anything to do with your setup, so that's just a coincidence. Fixes will need to be made to the code. Essentially, we don't export global namespaces containing types anymore at all. You now import every type, which is consistent with other TypeScript code. The other errors are due to TypeScript lacking type information on your config schema.

I'll make a pull request to your repository very soon that will fix this.

**Comment by shd101wyy** [comment]
Thank you very much ;)

**Comment by GlenCFL** [comment]
I've released an update to atom-typings that should get rid of all of the Config errors. I could make a pull request to your repository if you want, but the fix should be trivial so long as you update to `atom-typings` v1.21.6.

In the first screenshow, the fix is simply removing the `Atom.` prefix from the CompositeDisposable.

**Comment by shd101wyy** [comment]
Thanks for your effort! It works now.
